cluster:
  features:
    - etcd
    - etcd-ssl
    - fleet

  etcd-ssl:
    - mode: peer-only
    
  # generate a new token for each unique cluster from https://discovery.etcd.io/new
  etcd:
    - discovery: https://discovery.etcd.io/xyz

  ssh-authorized-keys:
    - ssh-rsa ...

  nodes:
    - mac: c8:60:00:cc:xx:8d
      hostname: coreos-1
      ip: 11.22.33.44
      metadata: datacenter=colo1

    - mac: c8:60:00:bb:aa:91
      hostname: coreos-2
      ip: 1.2.3.4
      metadata: datacenter=colo2
