cluster:
  features:
    - etcd2
    - etcd2-client-ssl
    - etcd2-ssl
    - fleet
    - mount
    - timezone
    - private-repository

  private-repository:
    insecure-addr: "10.0.0.0/8"

  timezone: Europe/Berlin

  # generate a new token for each unique cluster from https://discovery.etcd.io/new
  etcd2:
    discovery: https://discovery.etcd.io/xyz

  ssh_authorized_keys:
    - ssh-rsa ...

  update:
    reboot-strategy: off
    group: stable
    
  nodes:
    - mac: c8:60:00:cc:xx:8d
      hostname: coreos-1
      ip: 11.22.33.44
      
      fleet:
        metadata: dc=colo1,rack=rack1,disc=ssd,disc_amount=1,mem=32
        
      update:
        group: alpha
        
        
    - mac: c8:60:00:bb:aa:91
      hostname: coreos-2
      ip: 1.2.3.4
      mount:
        - dev: /dev/sdb
          mount-point: /mnt/sdb
          type: ext4
      fleet:
        metadata: dc=colo2,rack=rack2,disc=hdd,disc_amount=2,mem=32
